site_name: Omar Álvarez del Castillo
nav:
  - Home: index.md
  - Education: education.md
  - Experience: experience.md
  - Skills: skills.md
  - Selected Past Work: selectedpastwork.md

theme:
  name: material
  logo: images/wizeline_dark_isotype@2x.png
extra_css:
  - css/extra.css